NewsEdge.Web/Areas/Admin/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NewsEdge.DataAccess.Models;
using NewsEdge.Utilities.PaginationModels;

namespace NewsEdge.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    [ViewComponent(Name = "UsersCountViewComponent")]
    [AutoValidateAntiforgeryToken]
    public class UsersController : Controller
    {
        private UserManager<NewsEdgeUser> _userManager;

        public UsersController(UserManager<NewsEdgeUser> userManager)
        {
            _userManager = userManager;
        }

        //TODO : User edit and delete


        #region Read
        [Route("/Admin/Users/{pageId=1}")]
        public async Task<IActionResult> Index(int pageId = 1)
        {
            return View(nameof(Index), new ItemsWithPageDataViewModel<NewsEdgeUser>()
            {
                PageData = new()
                {
                    CurrentPage = pageId,
                    ItemPerPage = 30,
                    TotalItems = await _userManager.Users.CountAsync()
                },
                Entities = _userManager.Users.Skip((pageId - 1) * 30).Take(30)
            });
        }


        [Route("/Admin/Users/Detail/{id}")]
        public async Task<IActionResult> Detail([FromRoute] long id)
        {
            NewsEdgeUser user = await _userManager.FindByIdAsync(id.ToString());
            if (user is null)
            {
                return RedirectToPage("/Errors/NotFound");
            }
            return View(nameof(Detail), user);
        }
        #endregion

        #region Edit
        [Route("/Admin/Users/Edit/{id}")]
        [HttpGet]
        public async Task<IActionResult> Edit([FromRoute] long id)
        {
            return View(nameof(Edit), await FindUserByIdAsync(id));
        }


        [Route("/Admin/Users/AddOrDeleteUserFromRole/{role}/{userId}/{isDelete}")]
        [HttpGet]
        public async Task<bool> AddOrDeleteUserFromRole([FromRoute] string role, [FromRoute] long userId, [FromRoute] bool isDelete)
        {
            NewsEdgeUser user = await FindUserByIdAsync(userId);
            return isDelete switch
            {
                true => (await _userManager.RemoveFromRoleAsync(user, role)).Succeeded,
                false => (await _userManager.AddToRoleAsync(user, role)).Succeeded
            };
        }
        #endregion

        #region ViewComponent
        public async Task<string> InvokeAsync()
        {
            return (await _userManager.Users.CountAsync()).ToString();
        }
        #endregion


        #region Tools

        [NonAction]
        private async Task<NewsEdgeUser> FindUserByIdAsync(long id)
        {
            return await _userManager.FindByIdAsync(id.ToString());
        }

        #endregion

    }
}

NewsEdge.Web/Pages/User/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NewsEdge.Web.Pages.User;

[Authorize]
public class IndexModel : PageModel
{
    public void OnGet()
    {
    }
}

NewsEdge.Web/Areas/Admin/Views/Users/Edit.cshtml
@{
    ViewBag.Title = $"Editing {Model.UserName} data";
    var usersRole = await userManager.GetRolesAsync(Model);
}
@model NewsEdgeUser
@inject UserManager<NewsEdgeUser> userManager
@inject RoleManager<IdentityRole<long>> roleManager
@section css
    {
    <link href="/app-assets/vendors/css/sweetalert2.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/switchery.min.css">
}
<section>
    <a class="btn btn-success" asp-area="Admin" asp-controller="Users" asp-action="Index">Back</a>
    <div class="row justify-content-md-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title-wrap bar-primary">
                        <h4 class="card-title" id="basic-layout-card-center">ویرایش اطلاعات کاربر @Model.UserName</h4>
                    </div>
                </div>
                <div class="card-body">
                    <div class="px-3">
                        <form class="form">
                            <div class="form-body">

                                <div class="form-group">
                                    <label for="eventRegInput1">کنترل سطوح دسترسی</label>
                                    <ul>
                                        @foreach (IdentityRole<long> role in roleManager.Roles)
                                        {
                                            <li>
                                                <div class="form-group pb-1">
                                                    <input type="checkbox" id="switchery" class="switchery" checked="@(usersRole.Any(r => r.Equals(role.Name)))"
                                                       onchange="AddOrDeleteFromRole('@(role.Name)', @Model.Id, '@(usersRole.Any(r => r.Equals(role.Name)))')" />
                                                    <label for="switchery" class="font-medium-2 text-bold-600 ml-1">@role.Name</label>
                                                </div>
                                            </li>
                                        }
                                    </ul>
                                </div>

                                <div class="form-group">
                                    <label for="eventRegInput2">عنوان</label>
                                    <input type="text" id="eventRegInput2" class="form-control" name="title">
                                </div>

                                <div class="form-group">
                                    <label for="eventRegInput3">شرکت</label>
                                    <input type="text" id="eventRegInput3" class="form-control" name="company">
                                </div>

                                <div class="form-group">
                                    <label for="eventRegInput4">ایمیل</label>
                                    <input type="email" id="eventRegInput4" class="form-control" name="email">
                                </div>

                                <div class="form-group">
                                    <label for="eventRegInput5">شماره تماس</label>
                                    <input type="tel" id="eventRegInput5" class="form-control" name="contact">
                                </div>

                                <div class="form-group">
                                    <label>مشتری های موجود</label>
                                    <div class="input-group">
                                        <div class="custom-control custom-radio display-inline-block">
                                            <input type="radio" id="customRadioInline4" name="customRadioInline3" class="custom-control-input">
                                            <label class="custom-control-label" for="customRadioInline4">بله</label>
                                        </div>
                                        <div class="custom-control custom-radio display-inline-block">
                                            <input type="radio" id="customRadioInline3" checked="" name="customRadioInline3" class="custom-control-input">
                                            <label class="custom-control-label" for="customRadioInline3">خیر</label>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-actions center">
                                <button type="button" class="btn btn-danger mr-1">
                                    <i class="icon-trash"></i> لغو
                                </button>
                                <button type="button" class="btn btn-success">
                                    <i class="icon-note"></i> ذخیره
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section script
    {
    <script src="/app-assets/vendors/js/sweetalert2.min.js"></script>
    <script src="/app-assets/vendors/js/switchery.min.js"></script>
    <script src="/app-assets/js/switch.min.js"></script>
    <script>

        function AddOrDeleteFromRole(role, userId, type) {
            $.get("/Admin/Users/AddOrDeleteUserFromRole/" + role + "/" + userId + "/" + type, function (result) {
                if (result == true) {
                    swal({
                        title: 'موفق',
                        text: "عملیات با موفقیت انجام شد",
                        type: 'success',
                        confirmButtonColor: '#0CC27E',
                        confirmButtonText: 'تائید'
                    }).then(function (isConfirm) {
                        if (isConfirm) {
                            document.location.reload();
                        }
                    }).catch(swal.noop);
                }
                else {
                    swal("شکست", "عملیات با شکست مواجه گشت.", "error").done();
                }
            });
        }

    </script>
}

NewsEdge.Web/Areas/Admin/Views/Users/Index.cshtml
@{
    ViewBag.Title = "Users";
    int rowNumber = 1;
}

@model ItemsWithPageDataViewModel<NewsEdgeUser>
<section id="extended">
    <a class="btn btn-sm btn-info" asp-area="Admin" asp-controller="Home" asp-action="Index">
        <i class="fa fa-arrow-left"></i>
    </a>
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title-wrap bar-success">
                    <h4 class="card-title">کاربران سایت</h4>
                </div>
            </div>
            <div class="card-body">
                <div class="card-block">
                    <table class="table table-responsive-md text-center">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>نام کاربری</th>
                                <th>نام واقعی</th>
                                <th>ایمیل</th>
                                <th>شماره تلفن همراه</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (NewsEdgeUser user in Model.Entities)
                            {
                                <tr>
                                    <td>@rowNumber</td>
                                    <td>@user.UserName</td>
                                    <td>@user.RealName</td>
                                    <td class="@(user.EmailConfirmed ? "bg-success" : "bg-danger") text-white">@user.Email</td>
                                    <td class="@(user.PhoneNumberConfirmed ? "bg-success" : "bg-danger") text-white">@user.PhoneNumber</td>
                                    <td>
                                        <a asp-area="Admin" asp-controller="Users" asp-action="Edit" asp-route-id="@user.Id" class="success p-0" data-original-title="Edit user" title="Edit">
                                            <i class="fa fa-pencil font-medium-3 mr-2"></i>
                                        </a>
                                        <a asp-area="Admin" asp-controller="Users" asp-action="Detail" asp-route-id="@user.Id" class="primary p-0" data-original-title="Delete Detail" title="Detail">
                                            <i class="fa fa-file-o font-medium-3 mr-2"></i>
                                        </a>
                                    </td>
                                </tr>
                                _ = rowNumber++;
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <nav aria-label="Page navigation mb-3" page-data="@Model.PageData"></nav>
            </div>
        </div>
    </div>
</section>