NewsEdge.Web/Components/FooterMostViewedViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NewsEdge.DataAccess.Repositories.NewsRepositories;

namespace NewsEdge.Web.Components
{
    public class FooterMostViewedViewComponent : ViewComponent
    {
        private INewsRepository _newsRepository;

        public FooterMostViewedViewComponent(INewsRepository newsRepository)
        {
            _newsRepository = newsRepository;
        }

        public IViewComponentResult Invoke()
        {
            return View(_newsRepository.GetHotNews(3));
        }
    }
}

NewsEdge.Web/Components/HeaderFeedViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NewsEdge.DataAccess.Repositories.NewsRepositories;

namespace NewsEdge.Web.Components
{
    public class HeaderFeedViewComponent : ViewComponent
    {
        private INewsRepository _newsRepository;

        public HeaderFeedViewComponent(INewsRepository newsRepository)
        {
            _newsRepository = newsRepository;
        }

        public IViewComponentResult Invoke()
        {
            return View(_newsRepository.GetHotNews(3));
        }
        
    }
}

NewsEdge.Web/Components/MainMenuNavbarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NewsEdge.DataAccess.Models.Context;

namespace NewsEdge.Web.Components;

public class MainMenuNavbarViewComponent : ViewComponent
{
    private NewsEdgeContext _context;

    public MainMenuNavbarViewComponent(NewsEdgeContext context)
    {
        _context = context;
    }


    public IViewComponentResult Invoke()
    {
        return View(_context.Categories);
    }
}

NewsEdge.Web/Controllers/ArchiveController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage;
using NewsEdge.DataAccess.Repositories.CategoryRepository;
using NewsEdge.DataAccess.Repositories.NewsRepositories;
using NewsEdge.Utilities.TagHelpers;

namespace NewsEdge.Web.Controllers;

public class ArchiveController : Controller
{
    private INewsRepository _newsRepository;
    private ICategoryRepository _categoryRepository;

    public ArchiveController(INewsRepository newsRepository, ICategoryRepository categoryRepository)
    {
        _newsRepository = newsRepository;
        _categoryRepository = categoryRepository; 
    }

    [Route("/Archive")]
    [HttpGet]
    public async Task<IActionResult> Index([FromQuery] string selectedCategory = "", [FromQuery]string text = "", [FromQuery]int pageId = 1)
    {
        ViewBag.Text = text;
        ViewBag.Categories = _categoryRepository.GetAll().ToList();
        ViewBag.SelectedCategory = selectedCategory;
        ViewBag.PageId = pageId;
        ViewBag.PageData = new PageData()
        {
            CurrentPage = pageId,
            ItemPerPage = 6,
            TotalItems = (int)(await _newsRepository.CountAsync())
        };
        return View(nameof(Index), await _newsRepository.GetArchive(text, int.TryParse(selectedCategory, out int result) ? result : 0, pageId));
    }
}

NewsEdge.Web/Views/Shared/_Layout.cshtml
@using NewsEdge.Utilities.Convertor;
<!DOCTYPE html>
<html class="no-js" lang="fa">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@ViewBag.Title</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.png">
    <!-- Normalize CSS -->
    <link rel="stylesheet" href="/css/normalize.css">
    <!-- Main CSS -->
    <link rel="stylesheet" href="/css/main.css">
    <!-- Bootstrap rtl CSS -->
    <link rel="stylesheet" href="/css/bootstrap-rtl.min.css">
    <!-- Animate CSS -->
    <link rel="stylesheet" href="/css/animate.min.css">
    <!-- Font-awesome CSS-->
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <!-- Owl Caousel CSS -->
    <link rel="stylesheet" href="vendor/OwlCarousel/owl.carousel.min.css">
    <link rel="stylesheet" href="vendor/OwlCarousel/owl.theme.default.min.css">
    <!-- Main Menu CSS -->
    <link rel="stylesheet" href="/css/meanmenu.min.css">
    <!-- Magnific CSS -->
    <link rel="stylesheet" type="text/css" href="/css/magnific-popup.css">
    <!-- Switch Style CSS -->
    <link rel="stylesheet" href="/css/hover-min.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="/css/style.css">
    <!-- For IE -->
    <link rel="stylesheet" type="text/css" href="/css/ie-only.css">
    <!-- Modernizr Js -->
    <script src="js/modernizr-2.8.3.min.js"></script>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <base href="~/">
</head>

<body>
    <!--[if lt IE 8]>
    <p class="browserupgrade">شما از یک مرورگر <strong>تاریخ گذشته</strong> استفاده می کنید. لطفا <a href="http://browsehappy.com/">مرورگر خود را به روز کنید</a> تا تجربه بهتری داشته باشید.</p>
    <![endif]-->
    <!-- Add your site or application content here -->
    <!-- Preloader Start Here -->
    <div id="preloader">
        <div class="text-center middle">
            <div class="lds-ellipsis"><div></div><div></div><div></div><div></div></div>
        </div>
    </div>
    <!-- Preloader End Here -->
    <div id="wrapper" class="wrapper">
        <!-- Header Area Start Here -->
        <header>
            <div id="header-layout1" class="header-style1">
                <div class="main-menu-area bg-primarytextcolor header-menu-fixed" id="sticker">
                    <div class="container">
                        <div class="row no-gutters d-flex align-items-center">
                            <div class="col-lg-2 d-none d-lg-block">
                                <div class="logo-area">
                                    <a href="/">
                                        <img src="/img/logo.png" alt="logo" class="img-fluid">
                                    </a>
                                </div>
                            </div>
                            <vc:main-menu-navbar />
                            <div class="col-xl-2 col-lg-3 col-md-12 text-right position-static">
                                <div class="header-action-item">
                                    <ul>
                                        <li>
                                            <div class="header-search-light">
                                                <button class="search-button" data-toggle="modal" data-target="#myModal">
                                                    <i class="fa fa-search" aria-hidden="true"></i>
                                                </button>
                                            </div>
                                        </li>
                                        <li class="login_button">
                                            @if (!User.Identity.IsAuthenticated)
                                            {
                                                <a asp-page="/Account/Login" class="login-btn">
                                                    <i class="fa fa-user" aria-hidden="true"></i><span class="hidden-xs">ورود</span>
                                                </a>
                                            }
                                            else
                                            {
                                                <a class="login-btn" asp-page="/User/Index">
                                                    <i class="fa fa-user" aria-hidden="true"></i><span class="hidden-xs">داشبورد</span>
                                                </a>
                                            }
                                        </li>
                                        <li>
                                            <div id="side-menu-trigger" class="offcanvas-menu-btn">
                                                <a href="#" class="menu-bar">
                                                    <span></span>
                                                    <span></span>
                                                    <span></span>
                                                </a>
                                                <a href="#" class="menu-times close">
                                                    <span></span>
                                                    <span></span>
                                                </a>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Header Area End Here -->
        <!-- News Feed Area Start Here -->
        <section class="bg-accent border-bottom add-top-margin">
            <div class="container">
                <div class="row no-gutters d-flex align-items-center">
                    <div class="col-lg-2 col-md-3 col-sm-4 col-6">
                        <div class="topic-box topic-box-margin">اخبار داغ</div>
                    </div>
                    <vc:header-feed />
                </div>
            </div>
        </section>
        <!-- News Feed Area End Here -->
        <!-- News Info List Area Start Here -->
        <section class="bg-body">
            <div class="container">
                <ul class="news-info-list text-center--md">
                    <li>
                        <i class="fa fa-map-marker" aria-hidden="true"></i>ایران
                    </li>
                    <li>
                        <i class="fa fa-calendar" aria-hidden="true"></i>@DateTime.Now.ToShamsi()
                    </li>
                </ul>
            </div>
        </section>
        <!-- News Info List Area End Here -->
        @if (IsSectionDefined("PageBanner"))
        {
            @await RenderSectionAsync("PageBanner")
        }

        @RenderBody()


        <footer>
            <div class="footer-area-top">
                <div class="container">
                    <div class="row">
                        <vc:footer-most-viewed />
                        <vc:footer-popular-category />
                        <div class="col-xl-4 col-lg-5 col-md-12 col-sm-12">
                            <div class="footer-box">
                                <h2 class="title-bold-light title-bar-left text-uppercase">درباره برنامه نویس</h2>
                                <p class="text-white">
                                    مهدی عالی هستم الان که اینو مینویسم 18 سالمه از تبریز. از 15 سالگی برنامه نویسی رو شروع کردم و الان یک سال هست که به صورت حرفه ای دارم کار میکنم. 
                                    شماره تماس من : 09052730661 - ایمیل من : mahdi1383harold@outlook.com - تلگرام : @@microsoftlover
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-area-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-12 text-center">
                            <a href="/" class="footer-logo img-fluid">
                                <img src="/img/logo.png" alt="logo" class="img-fluid">
                            </a>
                            <p>برنامه نویسی شده با ❤ توسط مهدی عالی</p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Footer Area End Here -->
        <!-- Modal Start-->
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">×</button>
                        <div class="title-login-form">جستجو خبر</div>
                    </div>
                    <div class="modal-body">
                        <div class="login-form">
                            <form asp-controller="Archive" asp-action="Index" method="get">
                                <input type="text" name="text" placeholder="عنوان خبر">
                                <button type="submit">جستجو</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Modal End-->
        <!-- Offcanvas Menu Start -->
        <div id="offcanvas-body-wrapper" class="offcanvas-body-wrapper">
            <div id="offcanvas-nav-close" class="offcanvas-nav-close offcanvas-menu-btn">
                <a href="#" class="menu-times re-point">
                    <span></span>
                    <span></span>
                </a>
            </div>
            <div class="offcanvas-main-body">
                <ul id="accordion" class="offcanvas-nav panel-group">
                    <li>
                        <a asp-controller="Archive" asp-action="Index">
                            <i class="fa fa-archive" aria-hidden="true"></i>آرشیو
                        </a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a asp-page="/Account/LogOut">
                                <i class="fa fa-power-off" aria-hidden="true"></i>خروج از حساب
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </div>
        <!-- Offcanvas Menu End -->
    </div>
    <!-- Wrapper End -->
    <!-- jquery-->
    <script src="/js/jquery-2.2.4.min.js" type="text/javascript"></script>
    <!-- Plugins js -->
    <script src="/js/plugins.js" type="text/javascript"></script>
    <!-- Popper js -->
    <script src="/js/popper.js" type="text/javascript"></script>
    <!-- Bootstrap js -->
    <script src="/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- WOW JS -->
    <script src="/js/wow.min.js"></script>
    <!-- Owl Cauosel JS -->
    <script src="/vendor/OwlCarousel/owl.carousel.min.js" type="text/javascript"></script>
    <!-- Meanmenu Js -->
    <script src="/js/jquery.meanmenu.min.js" type="text/javascript"></script>
    <!-- Srollup js -->
    <script src="/js/jquery.scrollUp.min.js" type="text/javascript"></script>
    <!-- jquery.counterup js -->
    <script src="/js/jquery.counterup.min.js"></script>
    <script src="/js/waypoints.min.js"></script>
    <!-- Isotope js -->

    <script src="/js/select2.min.js"></script>
    <script src="/js/isotope.pkgd.min.js" type="text/javascript"></script>
    <!-- Magnific Popup -->
    <script src="/js/jquery.magnific-popup.min.js"></script>
    <!-- Ticker Js -->
    <script src="/js/ticker.js" type="text/javascript"></script>
    <!-- Custom Js -->
    <script src="/js/main.js" type="text/javascript"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

    <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit"
            async defer>
    </script>


    <script src="_framework/Blazor.Server.js"></script>
    <script src="/Interop.js"></script>

    @if (IsSectionDefined("script"))
    {
        await RenderSectionAsync("script");
    }
</body>

</html>

NewsEdge.Web/Views/Shared/_ValidationPartial.cshtml
<script src="/lib/validation/jquery.validate.min.js"></script>
<script src="/lib/validation/jquery.validate.unobtrusive.min.js"></script>